-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 14:04:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pacotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pacotes` (
  `idPacotes` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome_pacote` VARCHAR(75) NOT NULL DEFAULT 'Estudante, Trabalhador, Comum',
  `custo` DECIMAL(4,2) NOT NULL,
  `prazo` DATETIME(6) NOT NULL,
  PRIMARY KEY (`idPacotes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuarios` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `palavra-passe` VARCHAR(25) NOT NULL,
  `ativo` TINYINT NULL,
  `utima_conexao` DATETIME(6) NULL,
  `idPacotes` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idusuarios`, `idPacotes`),
  INDEX `fk_usuario_Pacotes1_idx` (`idPacotes` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Pacotes1`
    FOREIGN KEY (`idPacotes`)
    REFERENCES `mydb`.`Pacotes` (`idPacotes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rota` (
  `idrota` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `terminal` VARCHAR(45) NOT NULL,
  `numero_trasportes` BIGINT(4) ZEROFILL NULL,
  PRIMARY KEY (`idrota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`motorista` (
  `idmotorista` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `cod_carta_de_coducao` VARCHAR(20) NOT NULL,
  `palavra-passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmotorista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proprietario` (
  `idproprietario` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproprietario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carro` (
  `idcarro` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `lotacao` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `cod_livrete` VARCHAR(60) NOT NULL,
  `idrota` INT ZEROFILL NOT NULL,
  `idmotorista` INT ZEROFILL NOT NULL,
  `idproprietario` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idcarro`, `idmotorista`, `idproprietario`),
  INDEX `fk_carro_rota1_idx` (`idrota` ASC) VISIBLE,
  INDEX `fk_carro_motorista1_idx` (`idmotorista` ASC) VISIBLE,
  INDEX `fk_carro_proprietario1_idx` (`idproprietario` ASC) VISIBLE,
  CONSTRAINT `fk_carro_rota1`
    FOREIGN KEY (`idrota`)
    REFERENCES `mydb`.`rota` (`idrota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_motorista1`
    FOREIGN KEY (`idmotorista`)
    REFERENCES `mydb`.`motorista` (`idmotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_proprietario1`
    FOREIGN KEY (`idproprietario`)
    REFERENCES `mydb`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `idadmin` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobrador` (
  `idcobrador` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NULL,
  `telefone` VARCHAR(16) NULL,
  PRIMARY KEY (`idcobrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_usuario` (
  `action` NVARCHAR(45) NOT NULL,
  `datetime` TIMESTAMP(6) NOT NULL,
  `idusuario_admin` INT NOT NULL,
  `idusuario1` INT NOT NULL,
  PRIMARY KEY (`idusuario_admin`, `idusuario1`),
  INDEX `fk_log_usuario_usuario1_idx` (`idusuario1` ASC) VISIBLE,
  CONSTRAINT `fk_log_usuario_usuario`
    FOREIGN KEY (`idusuario_admin`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_usuario_usuario1`
    FOREIGN KEY (`idusuario1`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_carro` (
  `idcarro` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `idmotorista` INT NOT NULL,
  `datetime` TIMESTAMP(6) NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcarro`, `idusuario`, `idmotorista`),
  INDEX `fk_log_carro_usuario1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_log_carro_motorista1_idx` (`idmotorista` ASC) VISIBLE,
  CONSTRAINT `fk_log_carro_carro1`
    FOREIGN KEY (`idcarro`)
    REFERENCES `mydb`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_carro_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_carro_motorista1`
    FOREIGN KEY (`idmotorista`)
    REFERENCES `mydb`.`motorista` (`idmotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_proprietario` (
  `idproprietario` INT NOT NULL,
  `idcarro` INT NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `datetime` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idproprietario`, `idcarro`),
  INDEX `fk_log_proprietario_carro1_idx` (`idcarro` ASC) VISIBLE,
  CONSTRAINT `fk_log_proprietario_proprietario1`
    FOREIGN KEY (`idproprietario`)
    REFERENCES `mydb`.`proprietario` (`idproprietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_proprietario_carro1`
    FOREIGN KEY (`idcarro`)
    REFERENCES `mydb`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log_admin` (
  `idadmin` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `datetime` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idadmin`),
  CONSTRAINT `fk_log_admin_admin1`
    FOREIGN KEY (`idadmin`)
    REFERENCES `mydb`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`claim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`claim` (
  `idclaim` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`idclaim`),
  INDEX `fk_claim_usuario1_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_claim_usuario1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobrador_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobrador_carro` (
  `idcobrador` INT ZEROFILL NOT NULL,
  `idcarro` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idcobrador`, `idcarro`),
  INDEX `fk_cobrador_has_carro_carro1_idx` (`idcarro` ASC) VISIBLE,
  INDEX `fk_cobrador_has_carro_cobrador1_idx` (`idcobrador` ASC) VISIBLE,
  CONSTRAINT `fk_cobrador_has_carro_cobrador1`
    FOREIGN KEY (`idcobrador`)
    REFERENCES `mydb`.`cobrador` (`idcobrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobrador_has_carro_carro1`
    FOREIGN KEY (`idcarro`)
    REFERENCES `mydb`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_carro` (
  `idusuarios` INT NOT NULL,
  `idcarro` INT NOT NULL,
  `idmotorista` INT NOT NULL,
  PRIMARY KEY (`idusuarios`, `idcarro`, `idmotorista`),
  INDEX `fk_usuario_has_carro_carro1_idx` (`idcarro` ASC, `idmotorista` ASC) VISIBLE,
  INDEX `fk_usuario_has_carro_usuario1_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_carro_usuario1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_carro_carro1`
    FOREIGN KEY (`idcarro` , `idmotorista`)
    REFERENCES `mydb`.`carro` (`idcarro` , `idmotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`claim_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`claim_admin` (
  `idclaim_admin` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `created` TIMESTAMP(6) NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`idclaim_admin`),
  INDEX `fk_claim_admin_admin1_idx` (`admin_idadmin` ASC) VISIBLE,
  CONSTRAINT `fk_claim_admin_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `mydb`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `idpagamento` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT 'EM_DINHEIRO,M-PESA, M-KESH, M-MOLA, IZI',
  `valor` DECIMAL(4,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `cod_pagamento` INT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viajem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viajem` (
  `idviajem` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `idmotorista` INT ZEROFILL NOT NULL,
  `idusuarios` INT ZEROFILL NOT NULL,
  `idcarro` INT ZEROFILL NOT NULL,
  `idpagamento` INT ZEROFILL NOT NULL,
  `avaliacao_usuario` TINYINT(5) NULL,
  `embarque` FLOAT(10,6) NULL,
  `desembarque` FLOAT(10,6) NULL,
  PRIMARY KEY (`idviajem`, `idmotorista`, `idusuarios`, `idcarro`, `idpagamento`),
  INDEX `fk_viajem_motorista1_idx` (`idmotorista` ASC) VISIBLE,
  INDEX `fk_viajem_usuario1_idx` (`idusuarios` ASC) VISIBLE,
  INDEX `fk_viajem_carro1_idx` (`idcarro` ASC) VISIBLE,
  INDEX `fk_viajem_pagamento1_idx` (`idpagamento` ASC) VISIBLE,
  CONSTRAINT `fk_viajem_motorista1`
    FOREIGN KEY (`idmotorista`)
    REFERENCES `mydb`.`motorista` (`idmotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajem_usuario1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajem_carro1`
    FOREIGN KEY (`idcarro`)
    REFERENCES `mydb`.`carro` (`idcarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajem_pagamento1`
    FOREIGN KEY (`idpagamento`)
    REFERENCES `mydb`.`pagamento` (`idpagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
